### ISSUE TITLE
LoAT is solving limit problems before finishing the simplification

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#10]
If I understand the output correctly, LoAT is not simplifying the whole program before solving limit problems anymore. Instead, it seems to solve the corresponding limit problem as soon as there is a path of length one from the start location. I think this is a good idea, but I've never heard of any plans to implement this feature. Hence, my question is if this behavior is intended.

**Comment by ffrohn** [comment]
I think I got that wrong and LoAT is just printing the asymptotic complexity of accelerated loops in landau-notation to stdout. True?

**Comment by mttnff** [comment]
As far as I know, none of the above is done by LoAT. The only case where the limit problem is solved before the program is fully simplified is when a timeout is reached (or will be reached soon). Then the simplification is done differently to produce at least some results as far as possible. Does this behaviour also occur if you increase the timeout?

If not, can you post some of LoAT's output? I'm not sure what 

> asymptotic complexity of accelerated loops in landau-notation

would look like, but I don't think this is printed at any point.

**Comment by ffrohn** [comment]
Wow, the example from #3 produces 215Mb output... I ran LoAT without timeout, so this cannot be the reason. Actually, it's not the complexity of accelerated loops, but LoAT indeed seems to solve limit problems already during the simplification.

`$ grep -m 1 -C 10 Complexity out.txt`

where `out.txt` is LoAT's stdout yields

`free_37 is not a program variable`
`free_44 is not a program variable`
`O(n^1)`

`6 infty var(s)`
`Finding lower bound for the solved cost.`
`COST:  1+16*free_35+21*free_77  ===>  1+19/200*n`
`solved cost: 1+19/200*n, degree: 1`
`Omega(n^1)`

`Complexity: Omega(n^(1/1))`

`solved cost: 1+19/200*n`
`cost: 1+16*free_35+21*free_77`
`Solved the initial limit problem. (1 solved problem(s))`
`Solution:`
`o2013 / 1/500*n`
`free_35 / 1/500*n`
`a1 / 1/1000*n`
`o2352 / 1/1000*n`
`i758 / 0`

This is clearly the output of the limit-problem-solving. So I checked where such an output occurs for the first time:

`$ grep -n -m 1 Complexity out.txt`
`26379:Complexity: Omega(n^(1/1))`

So it's in line 26379 of stdout. Now I checked when LoAT applies chaining:

`$ grep -n Chain out.txt`
`...`
`1230114:Chained simpled loops:`

So the last chaining-step is reported in line 1230114, which is far later than the first limit-problem-solving step.

**Comment by ffrohn** [comment]
By the way, I'm on the `limitsmt`-branch.

**Comment by mttnff** [comment]
Ok, I just checked the code and noticed that limit problems are indeed solved in an intermediate step when _pruning_ is performed. If I recall correctly then the original motivation was to remove transitions that have a low complexity (i.e. we are somewhat greedy) if the branching degree is above a certain limit. As one can easily have a transition with a high cost, which is however limited by the guard (e.g. cost `A^2` and guard `A=0`) the limit solving is included in this step.

If the repeated limit solving is a bottleneck in these examples, one might consider to disable pruning (via `PRUNING_ENABLE`) or to ignore the guard in this check (so we have a weaker but faster heuristic).

EDIT: If you pass the `--stats` flag to LoAT, you can see how often `Flowgraph::pruneTransitions` gets called, just to confirm that this is indeed the case here.

**Comment by ffrohn** [comment]
Ok, thanks for figuring this out. I'm currently rerunning with `--stats` (but it takes a while). It's not clear to me if changing LoAT's strategy will make things better or worse, so let's just leave it as it is. Anyway, it's good to know where these intermediate limit problems come from.

**Comment by ffrohn** [comment]
Contract[Unsat]: 8
 ---- FlowGraph::chainLinear ----
 ---- FlowGraph::accelerateSimpleLoops ----
 ---- FlowGraph::chainSimpleLoops ----
 ---- FlowGraph::chainLinear ----
 ---- FlowGraph::chainBranches ----
 ---- FlowGraph::eliminateALocation ----
Contract[Linear]: 45
 ---- Flowgraph::pruneTransitions ----
Pruned[Removed]: 54
 ---- FlowGraph::accelerateSimpleLoops ----
Loop[NoRank]: 3
 ---- FlowGraph::chainSimpleLoops ----
Contract[Linear]: 15
 ---- FlowGraph::chainLinear ----
 ---- FlowGraph::accelerateSimpleLoops ----
 ---- FlowGraph::chainSimpleLoops ----
 ---- FlowGraph::chainLinear ----
 ---- FlowGraph::chainBranches ----
Contract[Branched]: 25
Contract[Unsat]: 75
 ---- Flowgraph::pruneTransitions ----
Pruned[Removed]: 25
NOTE: Contract UNSATs: 1156
CRITICAL: Loop failures: 17
 ======== STATS =========

WORST_CASE(Omega(n^1),?)
