### ISSUE TITLE
Telling "unbounded" and "non-terminating" apart

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#11]
It would be great to see the difference between "the ITS is non-terminating" and "the complexity of the ITS is unbounded" in the output. LoAT could, e.g., print `NO` in the former and `WORST_CASE(INF, ?)` in the latter case. This would be (more or less) consistent with the WST-conventions.

**Comment by mttnff** [comment]
Implemented in 1d7dabe9b0762eba3387683e28216a25da2662c1 (on master). LoAT now outputs `NO` for nontermination and `WORST_CASE(INF,?)` for unbounded runtime.

**Comment by ffrohn** [comment]
Great, thanks!
