### ISSUE TITLE
Invalid numeric constant (value too large)`

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#12]
I attached an interesting example, where LoAT aborts with the error:

`terminate called after throwing an instance of 'Expression::GinacZ3ConversionError'`
`  what():  Invalid numeric constant (value too large)`
[strange.txt](https://github.com/aprove-developers/LoAT/files/577848/strange.txt)

**Comment by mttnff** [comment]
I guess we can't completely avoid such issues*, but I've switched from `int` to `long` when converting expressions to Z3 in 31ebc503e (on the `loat2` branch). This allows us to handle the above example and prove nontermination.

---

(*) we could try to catch such exceptions, but we would have to change a lot of code to properly handle them (the conversion to Z3 is currently not assumed to fail) and I don't have the time to work on this right now. We can come back to this if we have examples where this actually happens, so I'm closing this for now.
