### ISSUE TITLE
don't solve the same limit problem over and over again

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#2]
The simplified program often contain several transitions with identical guards and costs. In these cases, LoAT should drop all but one of them.

**Comment by mttnff** [comment]
Implemented in 2dbd0d3064ef054dc5690315c2f04e030b79dc8b and 72c989d308ff0b8325ceaefb1ecc40345fa6c608.

This also includes a bugfix concerning duplicate transitions with slightly different cost, which in rare cases could yield unsound behaviour. The fix might have a minimal performance impact, but in my benchmark this was not noticeable.
