### ISSUE TITLE
solving limit problems via MAX-SMT

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#3]
1. create abstract polynomial p_x = c_x \* (n + n_0) + k_x for each x in V
2. apply sigma = {x | p_x} to all constraints, resulting in c
3. create hard constraint
    exists c_x k_x n_0 forall n: c
4. if the costs are linear, add
    cost sigma < costs sigma {n/n+1}
5. eliminate quantifiers using farkas' lemma
6. add soft constraints
    c_x > 0 resp. c_x < 0
   for all x in V(cost) where the term with the maximal degree of x in cost has a positive (resp. negative) coefficient;
   the weight is the maximal degree of x in cost

I think Farkas' cannot be applied because of the non-linear sub-expression c_x \* n_0. To solve that problem, we can just instantiate n_0 with a large constant.

**Comment by mttnff** [comment]
I just encountered the following problem with this approach:

`cost: x^2-y^2` and `guard: x > 0`

Using the above SMT encoding, `x = n` and `y = n` (or `y = -n`) is a possible solution that fulfils all (soft) constraints. However, `n^2 - n^2 = 0`.

One solution would be to assert `c_x - c_y != 0`. In general, this must be done for all variables of the same degree, as they can cancel out each other, which probably increases the SMT query quite a bit.

This can be done for `x^2-y^2` as all coefficients are numbers (`1` resp. `-1`). However, costs like `x*y` are much more complicated, as both `x` and `y` could be constant or linear in `n`, so one would need a case distinction for the resulting degree of `x*y`. Since we want to prefer the SMT encoding over the limit calculus, I think that we need to handle such cases (or we should not apply the SMT encoding then), as we would likely get less precise results (I just found such a situation in LoAT's examples).

**Comment by ffrohn** [comment]
What about the following (for costs without mixed terms): For each variable x, check the sign and the degree of the maximal x-term. If the sign is - and the degree is even, then the soft constraint is c_x=0. If the sign is - and the degree is odd, then the soft constraint is c_x<0. If the sign is +, then the soft constraint is c_x>0. So in the example above, the x-term with the highest degree has sign +, so we get the soft constraint c_x>0. The y-term with the highest degree has sign - and an even degree, so we get the soft constraint c_y=0. Maybe this can be generalized to costs with mixed terms somehow.

**Comment by mttnff** [comment]
Ah, I think I got a bit confused. This is indeed only a problem with even exponents, so your idea should work. We should however be careful with the weights, as just having `c_y = 0` is not very useful. Maybe we should add `c_x > 0 && c_y = 0` as a single soft-constraint?

A problem is that the solution might also be `c_x = 2` and `c_y = 1`, which cannot be found by this encoding. So again, we might lose examples compared to the limit problems. I think we could also use `c_x + 3*c_x' > c_y + 5*c_y'` if `x,x'` have sign `+` and `y,y'` have sign `-` (and even exponent) which should be applicable in all cases(?) Here, 3 and 5 just indicate that we must include the actual coefficient.

**Comment by ffrohn** [comment]
I think the latter is a good idea.

**Comment by mttnff** [comment]
A SMT encoding (with incremental queries instead of soft constraints) for linear guards and polynomial costs without mixed terms is implemented in the branch `limitsmt` for further testing.

**Comment by ffrohn** [comment]
Here's the result of a first test. This was a "just lower bounds" run on the smallest example from the first STAC-engagement.

Without SMT:
Crahed: 4
Constant: 13
Linear: 13
Infinite: 6
Time: 419 s

With SMT:
Crashed: 4
Constant: 7
Linear: 19
Infinite: 6
Time: 377 s

Note that the runtime is the combined runtime for AProVE's JBC-Frontend and LoAT. I think this is a remarkable improvement. Thanks, Matthias!

**Comment by ffrohn** [comment]
For the attached ITS, I get INF if I analyze it with the master branch (with a timeout of 600 seconds), but a linear bound if I analyze it with the limitsmt branch.

[ex.txt](https://github.com/aprove-developers/LoAT/files/555240/ex.txt)

**Comment by mttnff** [comment]
I have run your example three times and got `INF` twice and `O(n^1)` once. Unfortunately the example is too large to really look into it step by step. As GiNaC expressions are not deterministic (i.e. the order in additions or products can vary) we sometimes have nondeterministic behaviour of the limit solving (and maybe also the program simplification, but I think most of it for the limit problems). So it might be the case that the SMT encoding works, but the simplification before is different between the runs.

**Comment by ffrohn** [comment]
Ok, having some non-determinism is not a problem. Thanks for looking into it. I think the SMT-encoding should be merged into master, but it should be disabled by default and there should be a flag to enable it.

**Comment by mttnff** [comment]
Is now merged into master, the flag is `--limit-smt` (and is disabled by default).
