### ISSUE TITLE
parser does not like variable names with ticks

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#4]
Here's a minimal example that causes the parser to crash:

`(GOAL COMPLEXITY)`
`(STARTTERM (FUNCTIONSYMBOLS start))`
`(VAR x''' x')`
`(RULES`
`start() -> f() :|: x''' > 0`
`)`

**Comment by mttnff** [comment]
The problem was not related to the ticks (they get renamed to underscores, as GiNaC does not like them), but x''' was incorrectly parsed as x' (with some ticks behind) instead of x''' and then only some of the ticks were replaced. I'll push a bugfix soon.

**Comment by mttnff** [comment]
Fixed in the `cage` branch, which will soon be merged into `master` (see #5)
