### ISSUE TITLE
Active branches

### ISSUE THREAD

**Issue by mttnff** [aprove-developers/LoAT#5]
At the moment, we have several branches in this repo and I think we should clean up a bit. My guess is that the relevant branches are:
- `master`
- `cage`
- `recursion` / `recursionrework`

I guess `papermod` is obsolete, as `cage` is based on it. `jbc-experiments` was just for testing and can be deleted (unless someone disagrees). If the refactoring in `recursionrework` is complete (@boeker), we should merge it into `recursion`.

The `termcomp16` branch just marks the version for termcomp, so I would prefer to replace it by a tag to the corresponding commit in `cage`.

The `master` branch currently contains the **old** version of the **infinity check**, whereas `cage` has the limit problem calculus. Do we want to keep the old implementation, or should we merge `cage` into `master`?
Looking at the [diff](https://github.com/aprove-developers/LoAT/compare/master...cage) the main changes in `cage` are the limit calculus, some adaptions to bring the implementation closer to the paper, the new cost syntax (`-{lower,upper}>`) and to allow the cost `0`.

**Comment by ffrohn** [comment]
I think we should merge `cage` into `master`. Then `cage` and `papermod` are obsolete and can be removed. Replacing `termcomp16` by a tag is a good idea. I don't remember the reason for creating `jbc-experiments` but I'm not using it, so as far as I'm concerned, we can remove it.

**Comment by mttnff** [comment]
Cage is now merged into master and I will delete the obsolete branches.
