### ISSUE TITLE
Forbid variable names including operators or brackets

### ISSUE THREAD

**Issue by mttnff** [aprove-developers/LoAT#6]
Currently variable names with `+ - * ^ / < > = ( ) [ ] , : &` and spaces are allowed (and probably handled correctly in most cases), but I would like to forbid such names to avoid ambiguous situations. Are there any problems with this (should any of these characters be allowed)?

**Comment by ffrohn** [comment]
I think that's a good idea.

**Comment by mttnff** [comment]
Implemented in 2a6bbdfce92290e875c36d78ec9a1c1895e625fd
